# Generated by Django 4.1.7 on 2023-03-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
    ]
